import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react"
import SessionProviderWrapper from "@/authContent/sessionProviderWrapper";
import { Navbar } from "@/myComponents/navBar/page";
import { Toaster } from "sonner";
import { Footer } from "@/myComponents/Footer/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProviderWrapper>
          <Navbar/>
          <Toaster position="top-right" duration={1500}/>
          <main className="pt-16">{children}</main>
          <Footer/>
        </SessionProviderWrapper>
        
      </body>
    </html>
  );
}
